version: 2
updates:

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-security-minor-patch:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"